name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Prettier (Check)
        run: pnpm format --check

      - name: Lint Code
        run: pnpm lint

      - name: Build Project
        run: pnpm build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: next-build
          path: .next

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./  # If your project is not at the root, change this to your Next.js directory
          scope: your-vercel-scope  # Replace with your Vercel scope (username or team)
          alias-domains: your-custom-domain.com # Optional, if you have custom domains
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }} # Optional, if you use Vercel team
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} # Optional, if you have project ID

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test

  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Prettier (Check)
        run: pnpm format --check

      - name: Lint Code
        run: pnpm lint

      - name: Build Project
        run: pnpm build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: next-build
          path: .next

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./  # If your project is not at the root, change this to your Next.js directory
          scope: your-vercel-scope  # Replace with your Vercel scope (username or team)
          alias-domains: your-custom-domain.com # Optional, if you have custom domains
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }} # Optional, if you use Vercel team
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} # Optional, if you have project ID

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test

  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Prettier (Check)
        run: pnpm format --check

      - name: Lint Code
        run: pnpm lint

      - name: Build Project
        run: pnpm build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: next-build
          path: .next

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./packages/dapp
          scope: summitshare
          alias-domains: htpps://Summitshare.co
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }} 
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} 

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test

  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
